[package]
name = "tutor-db2"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
dotenvy = "0.15.6"
eyre = "0.6.8"
sqlx = { version = "0.6", features = ["runtime-tokio-rustls", "postgres", "chrono"] }
